jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug - List Files
        run: ls -la

      - name: Debug - Check mvnw file
        run: ls -l mvnw || echo "mvnw not found"

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Grant Execution Permission to Maven Wrapper
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify